package core;

import java.awt.CardLayout;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import ui.Iconos;

/**
 *
 * @author LENOVO
 */
public class VentanaJuego extends javax.swing.JFrame {

    static final String MENU = "menu";
    static final String JUEGO = "juego";
    static final String ARBOLES = "arboles";
    static final String ESTADISTICAS = "estadisticas";
    static final String AYUDA = "ayuda";

    private final GameEngine gameEngine;
    private final Map<String, Pantalla> pantallas = new LinkedHashMap<>();
    private String actual;
    private String retorno = MENU;

    public VentanaJuego(GameEngine gameEngine) {
        this.gameEngine = gameEngine;
        initComponents();
        setIconImage(Iconos.imagenAplicacion(64));
        setResizable(false);
        setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());

        registrar(MENU, new PantallaMenu(this, gameEngine));
        registrar(JUEGO, new PantallaJuego(this, gameEngine));
        registrar(ARBOLES, new PantallaArboles(this, gameEngine));
        registrar(ESTADISTICAS, new PantallaEstadisticas(this, gameEngine));
        registrar(AYUDA, new PantallaAyuda(this));

        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "volver");
        getRootPane().getActionMap().put("volver", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                volver();
            }
        });

        mostrar(MENU);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPantallas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alcalde Digital");

        panelPantallas.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelPantallas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrar(String nombre, Pantalla pantalla) {
        pantallas.put(nombre, pantalla);
        panelPantallas.add((JComponent) pantalla, nombre);
    }

    void mostrar(String nombre) {
        if (nombre.equals(actual)) {
            return;
        }
        boolean esSecundaria = ARBOLES.equals(nombre) || ESTADISTICAS.equals(nombre) || AYUDA.equals(nombre);
        if (esSecundaria && (MENU.equals(actual) || JUEGO.equals(actual))) {
            retorno = actual;
        }
        if (actual != null) {
            pantallas.get(actual).alOcultar();
        }
        actual = nombre;
        ((CardLayout) panelPantallas.getLayout()).show(panelPantallas, nombre);
        pantallas.get(nombre).alMostrar();
    }

    void volver() {
        if (ARBOLES.equals(actual) || ESTADISTICAS.equals(actual) || AYUDA.equals(actual)) {
            mostrar(retorno);
        } else if (JUEGO.equals(actual)) {
            mostrar(MENU);
        }
    }

    void salir() {
        dispose();
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPantallas;
    // End of variables declaration//GEN-END:variables
}
